AWSTemplateFormatVersion: '2010-09-09'
Description: 'another_betterthannothing_vpn - Disposable VPN infrastructure with WireGuard'

Parameters:
  VpcCidr:
    Type: String
    Default: '10.10.0.0/16'
    Description: 'CIDR block for the VPC (must be RFC 1918 private range)'
    AllowedPattern: '^(10\.(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){2}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/(1[6-9]|2[0-8])|172\.(1[6-9]|2[0-9]|3[0-1])\.(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){1}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/(1[6-9]|2[0-8])|192\.168\.(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){1}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/(1[6-9]|2[0-8]))'
    ConstraintDescription: 'Must be a valid RFC 1918 private CIDR block with prefix length between /16 and /28'

  InstanceType:
    Type: String
    Default: 't4g.nano'
    Description: 'EC2 instance type for the VPN server'

  InstanceArchitecture:
    Type: String
    Default: 'arm64'
    Description: 'CPU architecture for the instance (arm64 for t4g/m6g/c6g, x86_64 for t3/m5/c5)'
    AllowedValues:
      - 'arm64'
      - 'x86_64'

  VpnPort:
    Type: Number
    Default: 51820
    Description: 'Port number for VPN traffic'
    MinValue: 1024
    MaxValue: 65535

  VpnProtocol:
    Type: String
    Default: 'udp'
    Description: 'Protocol for VPN traffic'
    AllowedValues:
      - 'udp'
      - 'tcp'

  AllowedIngressCidr:
    Type: String
    Default: '0.0.0.0/0'
    Description: 'Source CIDR allowed to connect to the VPN port (use --my-ip for better security)'
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}'
    ConstraintDescription: 'Must be a valid CIDR block (e.g., 203.0.113.0/24 or 0.0.0.0/0)'

  UseSpotInstance:
    Type: String
    Default: 'false'
    Description: 'Use EC2 Spot instance instead of on-demand (lower cost but can be interrupted)'
    AllowedValues:
      - 'true'
      - 'false'

  AllocateEIP:
    Type: String
    Default: 'false'
    Description: 'Allocate an Elastic IP for persistent public IP address'
    AllowedValues:
      - 'true'
      - 'false'

Conditions:
  UseSpot: !Equals [!Ref UseSpotInstance, 'true']
  UseOnDemand: !Not [!Equals [!Ref UseSpotInstance, 'true']]
  ShouldAllocateEIP: !Equals [!Ref AllocateEIP, 'true']
  IsArm64: !Equals [!Ref InstanceArchitecture, 'arm64']

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpc'
        - Key: CostCenter
          Value: !Ref AWS::StackName

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [0, !Cidr [!Ref VpcCidr, 1, 8]]
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-subnet'
        - Key: CostCenter
          Value: !Ref AWS::StackName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-igw'
        - Key: CostCenter
          Value: !Ref AWS::StackName

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-rt'
        - Key: CostCenter
          Value: !Ref AWS::StackName

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  VpnSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${AWS::StackName}-vpn-sg'
      GroupDescription: 'Security group for VPN server - allows only VPN traffic'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: !Ref VpnProtocol
          FromPort: !Ref VpnPort
          ToPort: !Ref VpnPort
          CidrIp: !Ref AllowedIngressCidr
          Description: 'VPN traffic from allowed CIDR'
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: '0.0.0.0/0'
          Description: 'Allow all outbound traffic for SSM and package installation'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpn-sg'
        - Key: CostCenter
          Value: !Ref AWS::StackName

  VpnInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-vpn-instance-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpn-instance-role'
        - Key: CostCenter
          Value: !Ref AWS::StackName

  VpnInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${AWS::StackName}-vpn-instance-profile'
      Roles:
        - !Ref VpnInstanceRole

  # Launch Template for Spot instances
  VpnLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${AWS::StackName}-launch-template'
      LaunchTemplateData:
        ImageId: !If
          - IsArm64
          - '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64}}'
          - '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Arn: !GetAtt VpnInstanceProfile.Arn
        SecurityGroupIds:
          - !Ref VpnSecurityGroup
        MetadataOptions:
          HttpTokens: required
          HttpPutResponseHopLimit: 1
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 8
              VolumeType: gp3
              Encrypted: true
              DeleteOnTermination: true
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -euo pipefail
            
            # Update SSM agent if needed
            dnf install -y amazon-ssm-agent || yum install -y amazon-ssm-agent
            systemctl enable amazon-ssm-agent
            systemctl start amazon-ssm-agent
            
            # Set hostname
            hostnamectl set-hostname ${AWS::StackName}-vpn-server
            
            # Log completion
            echo "UserData script completed successfully" > /var/log/userdata-complete.log
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub '${AWS::StackName}-vpn-server'
              - Key: CostCenter
                Value: !Ref AWS::StackName
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Sub '${AWS::StackName}-vpn-volume'
              - Key: CostCenter
                Value: !Ref AWS::StackName

  # On-demand instance (when UseSpot is false)
  VpnInstanceOnDemand:
    Type: AWS::EC2::Instance
    Condition: UseOnDemand
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref VpnLaunchTemplate
        Version: !GetAtt VpnLaunchTemplate.LatestVersionNumber
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpn-server'
        - Key: CostCenter
          Value: !Ref AWS::StackName

  # Spot Fleet for Spot instances (when UseSpot is true)
  VpnSpotFleet:
    Type: AWS::EC2::SpotFleet
    Condition: UseSpot
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: !GetAtt SpotFleetRole.Arn
        TargetCapacity: 1
        TerminateInstancesWithExpiration: false
        Type: maintain
        LaunchTemplateConfigs:
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref VpnLaunchTemplate
              Version: !GetAtt VpnLaunchTemplate.LatestVersionNumber
            Overrides:
              - SubnetId: !Ref PublicSubnet
        TagSpecifications:
          - ResourceType: spot-fleet-request
            Tags:
              - Key: Name
                Value: !Sub '${AWS::StackName}-spot-fleet'
              - Key: CostCenter
                Value: !Ref AWS::StackName

  # IAM Role for Spot Fleet
  SpotFleetRole:
    Type: AWS::IAM::Role
    Condition: UseSpot
    Properties:
      RoleName: !Sub '${AWS::StackName}-spot-fleet-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: spotfleet.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-spot-fleet-role'
        - Key: CostCenter
          Value: !Ref AWS::StackName

  VpnEIP:
    Type: AWS::EC2::EIP
    Condition: ShouldAllocateEIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-eip'
        - Key: CostCenter
          Value: !Ref AWS::StackName

  # EIP Association for On-Demand instance
  VpnEIPAssociationOnDemand:
    Type: AWS::EC2::EIPAssociation
    Condition: ShouldAllocateEIP
    DependsOn: VpnInstanceOnDemand
    Properties:
      AllocationId: !GetAtt VpnEIP.AllocationId
      InstanceId: !If
        - UseOnDemand
        - !Ref VpnInstanceOnDemand
        - !Ref AWS::NoValue

Outputs:
  InstanceId:
    Description: 'EC2 instance ID of the VPN server (for on-demand instances)'
    Value: !If
      - UseOnDemand
      - !Ref VpnInstanceOnDemand
      - 'spot-fleet-managed'
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  SpotFleetId:
    Description: 'Spot Fleet Request ID (for spot instances)'
    Condition: UseSpot
    Value: !Ref VpnSpotFleet
    Export:
      Name: !Sub '${AWS::StackName}-SpotFleetId'

  PublicIp:
    Description: 'Public IP address of the VPN server'
    Value: !If
      - UseOnDemand
      - !If
        - ShouldAllocateEIP
        - !Ref VpnEIP
        - !GetAtt VpnInstanceOnDemand.PublicIp
      - 'spot-fleet-managed'
    Export:
      Name: !Sub '${AWS::StackName}-PublicIp'

  HasElasticIP:
    Description: 'Boolean indicating whether an Elastic IP was allocated'
    Value: !Ref AllocateEIP
    Export:
      Name: !Sub '${AWS::StackName}-HasElasticIP'

  VpcId:
    Description: 'VPC ID'
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'

  VpcCidr:
    Description: 'VPC CIDR block'
    Value: !Ref VpcCidr
    Export:
      Name: !Sub '${AWS::StackName}-VpcCidr'

  Region:
    Description: 'AWS Region where the stack is deployed'
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'

  VpnPort:
    Description: 'VPN listening port'
    Value: !Ref VpnPort
    Export:
      Name: !Sub '${AWS::StackName}-VpnPort'

  VpnProtocol:
    Description: 'VPN protocol (udp or tcp)'
    Value: !Ref VpnProtocol
    Export:
      Name: !Sub '${AWS::StackName}-VpnProtocol'

  InstanceArchitecture:
    Description: 'CPU architecture of the instance'
    Value: !Ref InstanceArchitecture
    Export:
      Name: !Sub '${AWS::StackName}-InstanceArchitecture'
