AWSTemplateFormatVersion: '2010-09-09'
Description: 'another_betterthannothing_vpn - Disposable VPN infrastructure with WireGuard'

Parameters:
  VpcCidr:
    Type: String
    Default: '10.10.0.0/16'
    Description: 'CIDR block for the VPC (must be RFC 1918 private range)'
    AllowedPattern: '^(10\.(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){2}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/(1[6-9]|2[0-8])|172\.(1[6-9]|2[0-9]|3[0-1])\.(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){1}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/(1[6-9]|2[0-8])|192\.168\.(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){1}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/(1[6-9]|2[0-8]))$'
    ConstraintDescription: 'Must be a valid RFC 1918 private CIDR block with prefix length between /16 and /28'

  InstanceType:
    Type: String
    Default: 't4g.nano'
    Description: 'EC2 instance type for the VPN server'

  VpnPort:
    Type: Number
    Default: 51820
    Description: 'Port number for VPN traffic'
    MinValue: 1024
    MaxValue: 65535

  VpnProtocol:
    Type: String
    Default: 'udp'
    Description: 'Protocol for VPN traffic'
    AllowedValues:
      - 'udp'
      - 'tcp'

  AllowedIngressCidr:
    Type: String
    Default: '0.0.0.0/0'
    Description: 'Source CIDR allowed to connect to the VPN port (use --my-ip for better security)'
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'
    ConstraintDescription: 'Must be a valid CIDR block (e.g., 203.0.113.0/24 or 0.0.0.0/0)'

  UseSpotInstance:
    Type: String
    Default: 'false'
    Description: 'Use EC2 Spot instance instead of on-demand (lower cost but can be interrupted)'
    AllowedValues:
      - 'true'
      - 'false'

Conditions:
  UseSpot: !Equals [!Ref UseSpotInstance, 'true']

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpc'
        - Key: costcenter
          Value: !Ref AWS::StackName

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [0, !Cidr [!Ref VpcCidr, 1, 8]]
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-subnet'
        - Key: costcenter
          Value: !Ref AWS::StackName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-igw'
        - Key: costcenter
          Value: !Ref AWS::StackName

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-rt'
        - Key: costcenter
          Value: !Ref AWS::StackName

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  VpnSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${AWS::StackName}-vpn-sg'
      GroupDescription: 'Security group for VPN server - allows only VPN traffic'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: !Ref VpnProtocol
          FromPort: !Ref VpnPort
          ToPort: !Ref VpnPort
          CidrIp: !Ref AllowedIngressCidr
          Description: 'VPN traffic from allowed CIDR'
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: '0.0.0.0/0'
          Description: 'Allow all outbound traffic for SSM and package installation'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpn-sg'
        - Key: costcenter
          Value: !Ref AWS::StackName

  VpnInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-vpn-instance-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpn-instance-role'
        - Key: costcenter
          Value: !Ref AWS::StackName

  VpnInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${AWS::StackName}-vpn-instance-profile'
      Roles:
        - !Ref VpnInstanceRole

  VpnInstance:
    Type: AWS::EC2::Instance
    Properties:
      # Use SSM parameter to get latest Amazon Linux 2023 AMI (ARM64 for t4g, x86_64 for others)
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64}}'
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref VpnInstanceProfile
      SecurityGroupIds:
        - !Ref VpnSecurityGroup
      SubnetId: !Ref PublicSubnet
      # Conditional Spot instance configuration
      InstanceMarketOptions: !If
        - UseSpot
        - MarketType: spot
          SpotOptions:
            SpotInstanceType: one-time
            InstanceInterruptionBehavior: terminate
        - !Ref AWS::NoValue
      # IMDSv2 enforcement
      MetadataOptions:
        HttpTokens: required
        HttpPutResponseHopLimit: 1
      # Encrypted root volume
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp3
            Encrypted: true
            DeleteOnTermination: true
      # Minimal UserData script
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euo pipefail
          
          # Update SSM agent if needed
          dnf install -y amazon-ssm-agent || yum install -y amazon-ssm-agent
          systemctl enable amazon-ssm-agent
          systemctl start amazon-ssm-agent
          
          # Set hostname
          hostnamectl set-hostname ${AWS::StackName}-vpn-server
          
          # Log completion
          echo "UserData script completed successfully" > /var/log/userdata-complete.log
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpn-server'
        - Key: costcenter
          Value: !Ref AWS::StackName

Outputs:
  InstanceId:
    Description: 'EC2 instance ID of the VPN server'
    Value: !Ref VpnInstance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  PublicIp:
    Description: 'Public IP address of the VPN server'
    Value: !GetAtt VpnInstance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIp'

  VpcId:
    Description: 'VPC ID'
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'

  VpcCidr:
    Description: 'VPC CIDR block'
    Value: !Ref VpcCidr
    Export:
      Name: !Sub '${AWS::StackName}-VpcCidr'

  Region:
    Description: 'AWS Region where the stack is deployed'
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'

  VpnPort:
    Description: 'VPN listening port'
    Value: !Ref VpnPort
    Export:
      Name: !Sub '${AWS::StackName}-VpnPort'

  VpnProtocol:
    Description: 'VPN protocol (udp or tcp)'
    Value: !Ref VpnProtocol
    Export:
      Name: !Sub '${AWS::StackName}-VpnProtocol'
